name: Development Deployment

on:
  push:
    branches: [ main ]

jobs:
  infrastructure:
    name: Infrastructure
    runs-on: ubuntu-latest
    environment: dev
    steps:

      # Checkout code
    - name: Checkount
      uses: actions/checkout@main

      # Log into Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.INFRASTRUCTURE_CREDENTIALS  }}

      # Deploy Bicep file
    - name: Deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./infra.bicep
        parameters: ./dev-infra.parameters.json
        failOnStdErr: false

  build_and_deploy_web:
    runs-on: ubuntu-latest
    name: Build and Deploy Moosta Web
    environment: dev

    steps:

    #Build and Deploy Blazor Web App
    - uses: actions/checkout@v2
    - name: Build And Deploy Azure Static Web App
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} 
        app_location: /src/Moost.Web
        app_artifact_location: wwwroot
        action: upload