name: Development Deployment

on:
  push:
    branches: [ main ]

jobs:
  infrastructure:
    runs-on: ubuntu-latest
    environment: dev
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
        with:
          creds: ${{ secrets.INFRASTRUCTURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ env.AZURE_RG }}
        template: ./infra.bicep
        failOnStdErr: false